#!/usr/bin/python

import Influenza

s = Influenza.Simulation()

def formatVect(v):
    s = "[ "
    for i in range(len(v)):
        if i == 0:
            s += "%s" % str(v[i])
        else:
            s += ", %s" % str(v[i])
    s += " ]"
    return s

for p in ("ages", "beta", "epsilon", "gamma", "nuUH", "nuUL", "nuVH", "nuVL",
          "sigma", "tau", "expectationOfLife", "population"):
    print "%s = %s" % (p, formatVect(getattr(s.parameters, p)))
    print
