#!/usr/bin/python

import os
import numpy
import pickle

contacts = {}
population = {}

for file in os.listdir('.'):
    if file.endswith('_contact.dat'):
        contacts[file[:-12]] = numpy.array([ map(float,
                                                 line.strip().split(' '))
                                             for line
                                             in open(file).readlines() ])

    elif file.endswith('_population.dat'):
        population[file[:-15]] = numpy.array([ float(line.strip())
                                               for line
                                               in open(file).readlines() ])

phiDict = {}

for key in contacts.keys():
    # divide by population
    phi0 = contacts[key] \
        / (numpy.ones(population[key].shape) * population[key]) \
        * sum(population[key])

    # make symmetric
    phiDict[key] = (phi0 + phi0.transpose()) / 2.0

# take mean of countries
phi = numpy.mean(phiDict.values(), 0)

# imbed in 17x17
Phi = numpy.empty((17, 17))
Phi[1 : 16, 1 : 16] = phi
Phi[0, 1 : 16] = phi[0, :]
Phi[1 : 16, 0] = phi[:, 0]
Phi[-1, 1 : 16] = phi[-1, :]
Phi[1 : 16, -1] = phi[:, -1]
Phi[0, 0] = phi[0, 0]
Phi[0, 16] = phi[0, 14]
Phi[16, 0] = phi[14, 0]
Phi[16, 16] = phi[14, 14]

pickle.dump(Phi, open('../phi.p', 'w'))
